### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by moostad** [akamud/vscode-caniuse#4]
I tried in javascript and css and I just get "Can I use: entry not found"!

**Comment by akamud** [comment]
It detects the word selected and queries caniuse.com for information about browser compatibility.  
For example, if I have this CSS file
```CSS
boo {
    outline: 1px;
    transform: 1;
    animation-name: 1;
    matrix: 1;
    keyframe: 1;
    border: 1px solid red;
    zoom: 1;
}
```
And I select `outline`, `transform`, `keyframe` or any other property and I activate "Can I Use" it will show the output from caniuse.com

What properties are you testing on?
